version: '3.9'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data-prod2:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db
    
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data-prod2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  
  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - static-data-prod2:/vol/static

volumes:
  static-data-prod2:
  postgres-data-prod2:
  
